name: pull-request

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: run golangci-lint
      uses: golangci/golangci-lint-action@v1.0.0
      with:
          version: v1.27

    - name: test
      run: make test

    - name: build
      run: make

    - name: notify slack success
      if: success()
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_COLOR: good
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: notify slack fail
      if: failure()
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_COLOR: danger
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
