name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v1.0.0
      with:
        # version of golangci-lint to use in form of v1.2.3
         version: v1.27
         args: .
