name: Release

on:
 release:

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: push
          uses: docker/build-push-action@v1
          with:
            name: weipengzhu/testaction/testaction
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            repository: docker.pkg.github.com
            tag_with_ref: true