name: Release

on:
 release:
  types: [ published, edit ]

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Push To Github Package
          uses: docker/build-push-action@v1
          with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: docker.pkg.github.com
            repository: weipengzhu/testaction/testaction
            tag_with_ref: true
        - name: notify slack success
          if: success()
          uses: rtCamp/action-slack-notify@v2.0.2
          env:
            SLACK_COLOR: good
            SLACK_MESSAGE: ${{ github.event }}
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

        - name: notify slack fail
          if: failure()
          uses: rtCamp/action-slack-notify@v2.0.2
          env:
            SLACK_COLOR: danger
            SLACK_MESSAGE: ${{ github.event.pull_request._links.html.href }}
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
