name: Release

on:
 release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
        - name: push
          uses: docker/build-push-action@v1
          with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: maymomo/test
          tag_with_ref: true