name: Release

on:
 release:
  types: [ published, edit ]

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Push To Github Package
          uses: docker/build-push-action@v1
          with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: docker.pkg.github.com
            repository: weipengzhu/testaction/testaction
            tag_with_ref: true