name: Release

on:
 release:

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: push
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: maymomo/test
            tag_with_ref: true